from gamelib import *

game = Game(658, 478 , "The Impossible Quiz")
s1 = Image("g1.png", game)
s2 = Image("g2.png", game)
g21 = Image("g21.png" , game)
g22 = Image("g22.png" , game)
g23 = Image("g23.png" , game)
s12 = Image("g12.png" , game)
q1 =Image("q1.png", game)
q11 = Image("q1-1.png", game)
q12 = Image("q1-2.png", game)
q13 = Image("q1-3.png", game)
q14 = Image("q1-4.png", game)
q2 = Image("q2.png" , game)
q21 = Image("q2-1.png" , game)
q22 = Image("q2-2.png" , game)
q23 = Image("q2-3.png", game)
q24 = Image("q2-4.png" , game)
q3 = Image("q3.png" , game)
q31 = Image("q3-1.png" , game)
q32 = Image("q3-2.png" , game)
q33 = Image("q3-3.png" , game)
q34 = Image("q3-4.png" , game)
q4 = Image("q4.png"  ,game)
q41 = Image("q4-1.png"  ,game)
q42 = Image("q4-2.png"  ,game)
q43 = Image("q4-3.png"  ,game)
q44 = Image("q4-4.png"  ,game)
q45 = Image("q4-5.png"  ,game)
q5 = Image("q5.png" , game)
q51 = Image("q5-1.png" , game)
q52 = Image("q5-2.png" , game)
q53 = Image("q5-3.png" , game)
q54 = Image("q5-4.png" , game)
q6 = Image("q6.png" , game)
q61 = Image("q6-1.png" , game)
q62 = Image("q6-2.png" , game)
q63 = Image("q6-3.png" , game)
q64 = Image("q6-4.png" , game)
q7 = Image("q7.png" , game)
q71 = Image("q7-1.png" , game)
q72 = Image("q7-2.png" , game)
q73 = Image("q7-3.png" , game)
q74 = Image("q7-4.png" , game)
q8 = Image("q8.png" , game)
q81 = Image("q8-1.png" , game)
q9 = Image("q9.png" , game)
q91 = Image("q9-1.png" , game)
q92 = Image("q9-2.png" , game)
q93 = Image("q9-3.png" , game)
q94 = Image("q9-4.png" , game)
i1 = Image("i1.png" , game)
b = Image("i12.png" , game)
c = Image("c.png" , game)
b2 = Image("c12.png" , game)
go = Image("gO.png",game)
gO = Image("gO1.png" , game)

'''    s2.makeVisible(0)
    gO.makeVisible(0)
    s12.makeVisible(0)
    g21.makeVisible(0)
    g22.makeVisible(0)
    g23.makeVisible(0)
    q1.makeVisible(0)
    i1.makeVisible(0)
    b.makeVisible(0)
    c.makeVisible(0)
    b2.makeVisible(0)
    q11.makeVisible(0)
    q12.makeVisible(0)
    q13.makeVisible(0)
    q14.makeVisible(0)
    q2.makeVisible(0)
    q21.makeVisible(0)
    q22.makeVisible(0)
    q23.makeVisible(0)
    q24.makeVisible(0)
    q3.makeVisible(0)
    q31.makeVisible(0)
    q32.makeVisible(0)
    q33.makeVisible(0)
    q34.makeVisible(0)
    q4.makeVisible(0)
    q41.makeVisible(0)
    q42.makeVisible(0)
    q43.makeVisible(0)
    q44.makeVisible(0)
    q45.makeVisible(0)
    q5.makeVisible(0)
    q51.makeVisible(0)
    q52.makeVisible(0)
    q53.makeVisible(0)
    q54.makeVisible(0)
    q6.makeVisible(0)
    q61.makeVisible(0)
    q62.makeVisible(0)
    q63.makeVisible(0)
    q64.makeVisible(0)
    q7.makeVisible(0)
    q71.makeVisible(0)
    q72.makeVisible(0)
    q73.makeVisible(0)
    q74.makeVisible(0)
    q8.makeVisible(0)
    q81.makeVisible(0)
    
    '''

s12.moveY(-8)
s12.moveX(5)


g21.moveTo(165,325)
g22.moveX(165)
g22.moveY(90)
g23.moveTo(165, 420)

X1 = -170
Y1 = 110
X2 = 170

q11.moveX(X1)
q12.moveX(X2)
q13.moveX(X1)
q13.moveY(Y1)
q14.moveY(Y1)
q14.moveX(X2)

q21.moveX(X2)
q22.moveX(X1)
q23.moveY(Y1)
q23.moveX(X1)
q24.moveX(X2)
q24.moveY(Y1)

q31.moveX(X1)
q32.moveX(X2)
q33.moveY(Y1)
q33.moveX(X1)
q34.moveX(X2)
q34.moveY(Y1)

q41.moveY(-120)
q41.moveX(10)
q42.moveX(X1)
q43.moveX(X2)
q44.moveX(X1+5)
q44.moveY(Y1+2)
q45.moveX(X2-3)
q45.moveY(Y1)

q51.moveX(X1+5)
q51.moveY(-8)
q52.moveX(X2-5)
q52.moveY(-3)
q53.moveX(X1+5)
q53.moveY(Y1+3)
q54.moveY(Y1)
q54.moveX(X2-5)

q61.moveX(X1)
q62.moveX(X2)
q63.moveY(Y1)
q63.moveX(X1)
q64.moveY(Y1)
q64.moveX(X2)

q71.moveX(X1)
q72.moveX(X2)
q73.moveY(Y1)
q73.moveX(X1)
q74.moveY(Y1)
q74.moveX(X2)

q81.moveX(17)
q81.moveY(39)

q91.moveX(X1)
q92.moveX(X2)
q93.moveY(Y1)
q93.moveX(X1)
q94.moveY(Y1)
q94.moveX(X2)

b.moveX(-265)
b.moveY(210)

b2.moveX(-265)
b2.moveY(210)

l=3

s1.draw()
s12.draw()
while not game.over:
    game.processInput()
    gO.makeVisible(0)
    if s12.collidedWith(mouse) and mouse.LeftButton:
        s2.makeVisible(1)
        gO.makeVisible(0)
        s12.makeVisible(0)
        g21.makeVisible(1)
        g22.makeVisible(1)
        g23.makeVisible(1)
        q1.makeVisible(0)
        i1.makeVisible(0)
        b.makeVisible(0)
        c.makeVisible(0)
        b2.makeVisible(0)
        q1.makeVisible(0)
        q11.makeVisible(0)
        q12.makeVisible(0)
        q13.makeVisible(0)
        q14.makeVisible(0)
        q2.makeVisible(0)
        q21.makeVisible(0)
        q22.makeVisible(0)
        q23.makeVisible(0)
        q24.makeVisible(0)
        q3.makeVisible(0)
        q31.makeVisible(0)
        q32.makeVisible(0)
        q33.makeVisible(0)
        q34.makeVisible(0)
        q4.makeVisible(0)
        q41.makeVisible(0)
        q42.makeVisible(0)
        q43.makeVisible(0)
        q44.makeVisible(0)
        q45.makeVisible(0)
        q5.makeVisible(0)
        q51.makeVisible(0)
        q52.makeVisible(0)
        q53.makeVisible(0)
        q54.makeVisible(0)
        q6.makeVisible(0)
        q61.makeVisible(0)
        q62.makeVisible(0)
        q63.makeVisible(0)
        q64.makeVisible(0)
        q7.makeVisible(0)
        q71.makeVisible(0)
        q72.makeVisible(0)
        q73.makeVisible(0)
        q74.makeVisible(0)
        q8.makeVisible(0)
        q81.makeVisible(0)
        q9.makeVisible(0)
        q91.makeVisible(0)
        q92.makeVisible(0)
        q93.makeVisible(0)
        q94.makeVisible(0)
        s2.draw()
        g21.draw()
        g22.draw()
        g23.draw()
    if g21.collidedWith(mouse) and mouse.LeftButton:
        s2.makeVisible(0)
        gO.makeVisible(0)
        s12.makeVisible(0)
        g21.makeVisible(0)
        g22.makeVisible(0)
        g23.makeVisible(0)
        q1.makeVisible(0)
        i1.makeVisible(0)
        b.makeVisible(0)
        c.makeVisible(0)
        b2.makeVisible(0)
        q1.makeVisible(1)
        q11.makeVisible(1)
        q12.makeVisible(1)
        q13.makeVisible(1)
        q14.makeVisible(1)
        q2.makeVisible(0)
        q21.makeVisible(0)
        q22.makeVisible(0)
        q23.makeVisible(0)
        q24.makeVisible(0)
        q3.makeVisible(0)
        q31.makeVisible(0)
        q32.makeVisible(0)
        q33.makeVisible(0)
        q34.makeVisible(0)
        q4.makeVisible(0)
        q41.makeVisible(0)
        q42.makeVisible(0)
        q43.makeVisible(0)
        q44.makeVisible(0)
        q45.makeVisible(0)
        q5.makeVisible(0)
        q51.makeVisible(0)
        q52.makeVisible(0)
        q53.makeVisible(0)
        q54.makeVisible(0)
        q6.makeVisible(0)
        q61.makeVisible(0)
        q62.makeVisible(0)
        q63.makeVisible(0)
        q64.makeVisible(0)
        q7.makeVisible(0)
        q71.makeVisible(0)
        q72.makeVisible(0)
        q73.makeVisible(0)
        q74.makeVisible(0)
        q8.makeVisible(0)
        q81.makeVisible(0)
        q9.makeVisible(0)
        q91.makeVisible(0)
        q92.makeVisible(0)
        q93.makeVisible(0)
        q94.makeVisible(0)
        q1.draw()
        q11.draw()
        q12.draw()
        q13.draw()
        q14.draw()
    if q14.collidedWith(mouse) and mouse.LeftButton:
        s2.makeVisible(0)
        gO.makeVisible(0)
        s12.makeVisible(0)
        g21.makeVisible(0)
        g22.makeVisible(0)
        g23.makeVisible(0)
        q1.makeVisible(0)
        i1.makeVisible(0)
        b.makeVisible(0)
        c.makeVisible(0)
        b2.makeVisible(0)
        q1.makeVisible(0)
        q11.makeVisible(0)
        q12.makeVisible(0)
        q13.makeVisible(0)
        q14.makeVisible(0)
        q2.makeVisible(1)
        q21.makeVisible(1)
        q22.makeVisible(1)
        q23.makeVisible(1)
        q24.makeVisible(1)
        q3.makeVisible(0)
        q31.makeVisible(0)
        q32.makeVisible(0)
        q33.makeVisible(0)
        q34.makeVisible(0)
        q4.makeVisible(0)
        q41.makeVisible(0)
        q42.makeVisible(0)
        q43.makeVisible(0)
        q44.makeVisible(0)
        q45.makeVisible(0)
        q5.makeVisible(0)
        q51.makeVisible(0)
        q52.makeVisible(0)
        q53.makeVisible(0)
        q54.makeVisible(0)
        q6.makeVisible(0)
        q61.makeVisible(0)
        q62.makeVisible(0)
        q63.makeVisible(0)
        q64.makeVisible(0)
        q7.makeVisible(0)
        q71.makeVisible(0)
        q72.makeVisible(0)
        q73.makeVisible(0)
        q74.makeVisible(0)
        q8.makeVisible(0)
        q81.makeVisible(0)
        q9.makeVisible(0)
        q91.makeVisible(0)
        q92.makeVisible(0)
        q93.makeVisible(0)
        q94.makeVisible(0)
        q2.draw()
        q24.draw()
        q23.draw()
        q22.draw()
        q21.draw()
    if q41.collidedWith(mouse) and mouse.LeftButton:
        s2.makeVisible(0)
        gO.makeVisible(0)
        s12.makeVisible(0)
        g21.makeVisible(0)
        g22.makeVisible(0)
        g23.makeVisible(0)
        q1.makeVisible(0)
        i1.makeVisible(0)
        b.makeVisible(0)
        c.makeVisible(0)
        b2.makeVisible(0)
        q1.makeVisible(0)
        q11.makeVisible(0)
        q12.makeVisible(0)
        q13.makeVisible(0)
        q14.makeVisible(0)
        q2.makeVisible(0)
        q21.makeVisible(0)
        q22.makeVisible(0)
        q23.makeVisible(0)
        q24.makeVisible(0)
        q3.makeVisible(0)
        q31.makeVisible(0)
        q32.makeVisible(0)
        q33.makeVisible(0)
        q34.makeVisible(0)
        q4.makeVisible(0)
        q41.makeVisible(0)
        q42.makeVisible(0)
        q43.makeVisible(0)
        q44.makeVisible(0)
        q45.makeVisible(0)
        q5.makeVisible(1)
        q51.makeVisible(1)
        q52.makeVisible(1)
        q53.makeVisible(1)
        q54.makeVisible(1)
        q6.makeVisible(0)
        q61.makeVisible(0)
        q62.makeVisible(0)
        q63.makeVisible(0)
        q64.makeVisible(0)
        q7.makeVisible(0)
        q71.makeVisible(0)
        q72.makeVisible(0)
        q73.makeVisible(0)
        q74.makeVisible(0)
        q8.makeVisible(0)
        q81.makeVisible(0)
        q9.makeVisible(0)
        q91.makeVisible(0)
        q92.makeVisible(0)
        q93.makeVisible(0)
        q94.makeVisible(0)
        q5.draw()
        q51.draw()
        q52.draw()
        q53.draw()
        q54.draw()
    if q53.collidedWith(mouse) and mouse.LeftButton:
        s2.makeVisible(0)
        gO.makeVisible(0)
        s12.makeVisible(0)
        g21.makeVisible(0)
        g22.makeVisible(0)
        g23.makeVisible(0)
        q1.makeVisible(0)
        i1.makeVisible(0)
        b.makeVisible(0)
        c.makeVisible(0)
        b2.makeVisible(0)
        q1.makeVisible(0)
        q11.makeVisible(0)
        q12.makeVisible(0)
        q13.makeVisible(0)
        q14.makeVisible(0)
        q2.makeVisible(0)
        q21.makeVisible(0)
        q22.makeVisible(0)
        q23.makeVisible(0)
        q24.makeVisible(0)
        q3.makeVisible(0)
        q31.makeVisible(0)
        q32.makeVisible(0)
        q33.makeVisible(0)
        q34.makeVisible(0)
        q4.makeVisible(0)
        q41.makeVisible(0)
        q42.makeVisible(0)
        q43.makeVisible(0)
        q44.makeVisible(0)
        q45.makeVisible(0)
        q5.makeVisible(0)
        q51.makeVisible(0)
        q52.makeVisible(0)
        q53.makeVisible(0)
        q54.makeVisible(0)
        q6.makeVisible(1)
        q61.makeVisible(1)
        q62.makeVisible(1)
        q63.makeVisible(1)
        q64.makeVisible(1)
        q7.makeVisible(0)
        q71.makeVisible(0)
        q72.makeVisible(0)
        q73.makeVisible(0)
        q74.makeVisible(0)
        q8.makeVisible(0)
        q81.makeVisible(0)
        q9.makeVisible(0)
        q91.makeVisible(0)
        q92.makeVisible(0)
        q93.makeVisible(0)
        q94.makeVisible(0)
        q6.draw()
        q61.draw()
        q62.draw()
        q63.draw()
        q64.draw()
    if q64.collidedWith(mouse) and mouse.LeftButton:
        s2.makeVisible(0)
        gO.makeVisible(0)
        s12.makeVisible(0)
        g21.makeVisible(0)
        g22.makeVisible(0)
        g23.makeVisible(0)
        q1.makeVisible(0)
        i1.makeVisible(0)
        b.makeVisible(0)
        c.makeVisible(0)
        b2.makeVisible(0)
        q1.makeVisible(0)
        q11.makeVisible(0)
        q12.makeVisible(0)
        q13.makeVisible(0)
        q14.makeVisible(0)
        q2.makeVisible(0)
        q21.makeVisible(0)
        q22.makeVisible(0)
        q23.makeVisible(0)
        q24.makeVisible(0)
        q3.makeVisible(0)
        q31.makeVisible(0)
        q32.makeVisible(0)
        q33.makeVisible(0)
        q34.makeVisible(0)
        q4.makeVisible(0)
        q41.makeVisible(0)
        q42.makeVisible(0)
        q43.makeVisible(0)
        q44.makeVisible(0)
        q45.makeVisible(0)
        q5.makeVisible(0)
        q51.makeVisible(0)
        q52.makeVisible(0)
        q53.makeVisible(0)
        q54.makeVisible(0)
        q6.makeVisible(0)
        q61.makeVisible(0)
        q62.makeVisible(0)
        q63.makeVisible(0)
        q64.makeVisible(0)
        q7.makeVisible(1)
        q71.makeVisible(1)
        q72.makeVisible(1)
        q73.makeVisible(1)
        q74.makeVisible(1)
        q8.makeVisible(0)
        q81.makeVisible(0)
        q9.makeVisible(0)
        q91.makeVisible(0)
        q92.makeVisible(0)
        q93.makeVisible(0)
        q94.makeVisible(0)
        q7.draw()
        q71.draw()
        q72.draw()
        q73.draw()
        q74.draw()
    if q72.collidedWith(mouse) and mouse.LeftButton:
        s2.makeVisible(0)
        gO.makeVisible(0)
        s12.makeVisible(0)
        g21.makeVisible(0)
        g22.makeVisible(0)
        g23.makeVisible(0)
        q1.makeVisible(0)
        i1.makeVisible(0)
        b.makeVisible(0)
        c.makeVisible(0)
        b2.makeVisible(0)
        q1.makeVisible(0)
        q11.makeVisible(0)
        q12.makeVisible(0)
        q13.makeVisible(0)
        q14.makeVisible(0)
        q2.makeVisible(0)
        q21.makeVisible(0)
        q22.makeVisible(0)
        q23.makeVisible(0)
        q24.makeVisible(0)
        q3.makeVisible(0)
        q31.makeVisible(0)
        q32.makeVisible(0)
        q33.makeVisible(0)
        q34.makeVisible(0)
        q4.makeVisible(0)
        q41.makeVisible(0)
        q42.makeVisible(0)
        q43.makeVisible(0)
        q44.makeVisible(0)
        q45.makeVisible(0)
        q5.makeVisible(0)
        q51.makeVisible(0)
        q52.makeVisible(0)
        q53.makeVisible(0)
        q54.makeVisible(0)
        q6.makeVisible(0)
        q61.makeVisible(0)
        q62.makeVisible(0)
        q63.makeVisible(0)
        q64.makeVisible(0)
        q7.makeVisible(0)
        q71.makeVisible(0)
        q72.makeVisible(0)
        q73.makeVisible(0)
        q74.makeVisible(0)
        q8.makeVisible(1)
        q81.makeVisible(1)
        q9.makeVisible(0)
        q91.makeVisible(0)
        q92.makeVisible(0)
        q93.makeVisible(0)
        q94.makeVisible(0)
        q8.draw()
        q81.draw()
    if q81.collidedWith(mouse) and mouse.LeftButton:
        s2.makeVisible(0)
        gO.makeVisible(0)
        s12.makeVisible(0)
        g21.makeVisible(0)
        g22.makeVisible(0)
        g23.makeVisible(0)
        q1.makeVisible(0)
        i1.makeVisible(0)
        b.makeVisible(0)
        c.makeVisible(0)
        b2.makeVisible(0)
        q1.makeVisible(0)
        q11.makeVisible(0)
        q12.makeVisible(0)
        q13.makeVisible(0)
        q14.makeVisible(0)
        q2.makeVisible(0)
        q21.makeVisible(0)
        q22.makeVisible(0)
        q23.makeVisible(0)
        q24.makeVisible(0)
        q3.makeVisible(0)
        q31.makeVisible(0)
        q32.makeVisible(0)
        q33.makeVisible(0)
        q34.makeVisible(0)
        q4.makeVisible(0)
        q41.makeVisible(0)
        q42.makeVisible(0)
        q43.makeVisible(0)
        q44.makeVisible(0)
        q45.makeVisible(0)
        q5.makeVisible(0)
        q51.makeVisible(0)
        q52.makeVisible(0)
        q53.makeVisible(0)
        q54.makeVisible(0)
        q6.makeVisible(0)
        q61.makeVisible(0)
        q62.makeVisible(0)
        q63.makeVisible(0)
        q64.makeVisible(0)
        q7.makeVisible(0)
        q71.makeVisible(0)
        q72.makeVisible(0)
        q73.makeVisible(0)
        q74.makeVisible(0)
        q8.makeVisible(0)
        q81.makeVisible(0)
        q9.makeVisible(1)
        q91.makeVisible(1)
        q92.makeVisible(1)
        q93.makeVisible(1)
        q94.makeVisible(1)
        q9.draw()
        q91.draw()
        q92.draw()
        q93.draw()
        q94.draw()
    if q92.collidedWith(mouse) and mouse.LeftButton:
        game.over = True
    if q31.collidedWith(mouse) and mouse.LeftButton:
        s2.makeVisible(0)
        gO.makeVisible(0)
        s12.makeVisible(0)
        g21.makeVisible(0)
        g22.makeVisible(0)
        g23.makeVisible(0)
        q1.makeVisible(0)
        i1.makeVisible(0)
        b.makeVisible(0)
        c.makeVisible(0)
        b2.makeVisible(0)
        q1.makeVisible(0)
        q11.makeVisible(0)
        q12.makeVisible(0)
        q13.makeVisible(0)
        q14.makeVisible(0)
        q2.makeVisible(0)
        q21.makeVisible(0)
        q22.makeVisible(0)
        q23.makeVisible(0)
        q24.makeVisible(0)
        q3.makeVisible(0)
        q31.makeVisible(0)
        q32.makeVisible(0)
        q33.makeVisible(0)
        q34.makeVisible(0)
        q4.makeVisible(1)
        q41.makeVisible(1)
        q42.makeVisible(1)
        q43.makeVisible(1)
        q44.makeVisible(1)
        q45.makeVisible(1)
        q5.makeVisible(0)
        q51.makeVisible(0)
        q52.makeVisible(0)
        q53.makeVisible(0)
        q54.makeVisible(0)
        q6.makeVisible(0)
        q61.makeVisible(0)
        q62.makeVisible(0)
        q63.makeVisible(0)
        q64.makeVisible(0)
        q7.makeVisible(0)
        q71.makeVisible(0)
        q72.makeVisible(0)
        q73.makeVisible(0)
        q74.makeVisible(0)
        q8.makeVisible(0)
        q81.makeVisible(0)
        q9.makeVisible(0)
        q91.makeVisible(0)
        q92.makeVisible(0)
        q93.makeVisible(0)
        q94.makeVisible(0)
        q4.draw()
        q41.draw()
        q42.draw()
        q43.draw()
        q44.draw()
        q45.draw()
    if q23.collidedWith(mouse) and mouse.LeftButton:
        s2.makeVisible(0)
        gO.makeVisible(0)
        s12.makeVisible(0)
        g21.makeVisible(0)
        g22.makeVisible(0)
        g23.makeVisible(0)
        q1.makeVisible(0)
        i1.makeVisible(0)
        b.makeVisible(0)
        c.makeVisible(0)
        b2.makeVisible(0)
        q11.makeVisible(0)
        q12.makeVisible(0)
        q13.makeVisible(0)
        q14.makeVisible(0)
        q2.makeVisible(0)
        q21.makeVisible(0)
        q22.makeVisible(0)
        q23.makeVisible(0)
        q24.makeVisible(0)
        q3.makeVisible(1)
        q31.makeVisible(1)
        q32.makeVisible(1)
        q33.makeVisible(1)
        q34.makeVisible(1)
        q4.makeVisible(0)
        q41.makeVisible(0)
        q42.makeVisible(0)
        q43.makeVisible(0)
        q44.makeVisible(0)
        q45.makeVisible(0)
        q5.makeVisible(0)
        q51.makeVisible(0)
        q52.makeVisible(0)
        q53.makeVisible(0)
        q54.makeVisible(0)
        q6.makeVisible(0)
        q61.makeVisible(0)
        q62.makeVisible(0)
        q63.makeVisible(0)
        q64.makeVisible(0)
        q7.makeVisible(0)
        q71.makeVisible(0)
        q72.makeVisible(0)
        q73.makeVisible(0)
        q74.makeVisible(0)
        q8.makeVisible(0)
        q81.makeVisible(0)
        q9.makeVisible(0)
        q91.makeVisible(0)
        q92.makeVisible(0)
        q93.makeVisible(0)
        q94.makeVisible(0)
        q31.draw()
        q32.draw()
        q33.draw()
        q34.draw()
        q3.draw()
    if g22.collidedWith(mouse) and mouse.LeftButton:
        s12.makeVisible(0)
        s2.makeVisible(0)
        g21.makeVisible(0)
        g22.makeVisible(0)
        g23.makeVisible(0)
        q1.makeVisible(0)
        c.makeVisible(0)
        b2.makeVisible(0)
        q11.makeVisible(0)
        q12.makeVisible(0)
        q13.makeVisible(0)
        q14.makeVisible(0)
        q2.makeVisible(0)
        q21.makeVisible(0)
        q22.makeVisible(0)
        q23.makeVisible(0)
        q24.makeVisible(0)
        i1.makeVisible(1)
        b.makeVisible(1)
        q31.makeVisible(0)
        q32.makeVisible(0)
        q33.makeVisible(0)
        q34.makeVisible(0)
        q4.makeVisible(0)
        q41.makeVisible(0)
        q42.makeVisible(0)
        q43.makeVisible(0)
        q44.makeVisible(0)
        q45.makeVisible(0)
        q5.makeVisible(0)
        q51.makeVisible(0)
        q52.makeVisible(0)
        q53.makeVisible(0)
        q54.makeVisible(0)
        q6.makeVisible(0)
        q61.makeVisible(0)
        q62.makeVisible(0)
        q63.makeVisible(0)
        q64.makeVisible(0)
        q7.makeVisible(0)
        q71.makeVisible(0)
        q72.makeVisible(0)
        q73.makeVisible(0)
        q74.makeVisible(0)
        q8.makeVisible(0)
        q81.makeVisible(0)
        q9.makeVisible(0)
        q91.makeVisible(0)
        q92.makeVisible(0)
        q93.makeVisible(0)
        q94.makeVisible(0)
        i1.draw()
        b.draw()
    if b.collidedWith(mouse) and mouse.LeftButton:
        s12.makeVisible(0)
        s2.makeVisible(1)
        g21.makeVisible(1)
        g22.makeVisible(1)
        g23.makeVisible(1)
        q1.makeVisible(0)
        i1.makeVisible(0)
        b.makeVisible(0)
        c.makeVisible(0)
        b2.makeVisible(0)
        q11.makeVisible(0)
        q12.makeVisible(0)
        q13.makeVisible(0)
        q14.makeVisible(0)
        q2.makeVisible(0)
        q21.makeVisible(0)
        q22.makeVisible(0)
        q23.makeVisible(0)
        q24.makeVisible(0)
        q31.makeVisible(0)
        q32.makeVisible(0)
        q33.makeVisible(0)
        q34.makeVisible(0)
        q4.makeVisible(0)
        q41.makeVisible(0)
        q42.makeVisible(0)
        q43.makeVisible(0)
        q44.makeVisible(0)
        q45.makeVisible(0)
        q5.makeVisible(0)
        q51.makeVisible(0)
        q52.makeVisible(0)
        q53.makeVisible(0)
        q54.makeVisible(0)
        q6.makeVisible(0)
        q61.makeVisible(0)
        q62.makeVisible(0)
        q63.makeVisible(0)
        q64.makeVisible(0)
        q7.makeVisible(0)
        q71.makeVisible(0)
        q72.makeVisible(0)
        q73.makeVisible(0)
        q74.makeVisible(0)
        q8.makeVisible(0)
        q81.makeVisible(0)
        q9.makeVisible(0)
        q91.makeVisible(0)
        q92.makeVisible(0)
        q93.makeVisible(0)
        q94.makeVisible(0)
        s2.draw()
    if g23.collidedWith(mouse) and mouse.LeftButton:
        s1.makeVisible(0)
        s2.makeVisible(0)
        s12.makeVisible(0)
        g21.makeVisible(0)
        g22.makeVisible(0)
        g23.makeVisible(0)
        q1.makeVisible(0)
        i1.makeVisible(0)
        b.makeVisible(0)
        c.makeVisible(1)
        b2.makeVisible(1)
        q11.makeVisible(0)
        q12.makeVisible(0)
        q13.makeVisible(0)
        q14.makeVisible(0)
        q2.makeVisible(0)
        q21.makeVisible(0)
        q22.makeVisible(0)
        q23.makeVisible(0)
        q24.makeVisible(0)
        q31.makeVisible(0)
        q32.makeVisible(0)
        q33.makeVisible(0)
        q34.makeVisible(0)
        q4.makeVisible(0)
        q41.makeVisible(0)
        q42.makeVisible(0)
        q43.makeVisible(0)
        q44.makeVisible(0)
        q45.makeVisible(0)
        q5.makeVisible(0)
        q51.makeVisible(0)
        q52.makeVisible(0)
        q53.makeVisible(0)
        q54.makeVisible(0)
        q6.makeVisible(0)
        q61.makeVisible(0)
        q62.makeVisible(0)
        q63.makeVisible(0)
        q64.makeVisible(0)
        q7.makeVisible(0)
        q71.makeVisible(0)
        q72.makeVisible(0)
        q73.makeVisible(0)
        q74.makeVisible(0)
        q8.makeVisible(0)
        q81.makeVisible(0)
        q9.makeVisible(0)
        q91.makeVisible(0)
        q92.makeVisible(0)
        q93.makeVisible(0)
        q94.makeVisible(0)
        c.draw()
        b2.draw()
    if b2.collidedWith(mouse) and mouse.LeftButton:
        s12.makeVisible(0)
        s2.makeVisible(1)
        g21.makeVisible(1)
        g22.makeVisible(1)
        g23.makeVisible(1)
        q1.makeVisible(0)
        i1.makeVisible(0)
        b.makeVisible(0)
        c.makeVisible(0)
        b2.makeVisible(0)
        q11.makeVisible(0)
        q12.makeVisible(0)
        q13.makeVisible(0)
        q14.makeVisible(0)
        q2.makeVisible(0)
        q21.makeVisible(0)
        q22.makeVisible(0)
        q23.makeVisible(0)
        q24.makeVisible(0)
        q31.makeVisible(0)
        q32.makeVisible(0)
        q33.makeVisible(0)
        q34.makeVisible(0)
        q4.makeVisible(0)
        q41.makeVisible(0)
        q42.makeVisible(0)
        q43.makeVisible(0)
        q44.makeVisible(0)
        q45.makeVisible(0)
        q5.makeVisible(0)
        q51.makeVisible(0)
        q52.makeVisible(0)
        q53.makeVisible(0)
        q54.makeVisible(0)
        q6.makeVisible(0)
        q61.makeVisible(0)
        q62.makeVisible(0)
        q63.makeVisible(0)
        q64.makeVisible(0)
        q7.makeVisible(0)
        q71.makeVisible(0)
        q72.makeVisible(0)
        q73.makeVisible(0)
        q74.makeVisible(0)
        q8.makeVisible(0)
        q81.makeVisible(0)
        q9.makeVisible(0)
        q91.makeVisible(0)
        q92.makeVisible(0)
        q93.makeVisible(0)
        q94.makeVisible(0)
        s2.draw()
    if l <= 0:
        game.over = True
    game.update(60)
game.quit()
